### ISSUE TITLE
SSL certificate check notifies about DDU's

### ISSUE THREAD

**Issue by ZTRossouw** [juliusloman/dynatrace-oneagent-plugin-sslcertcheck#6]
When installing the SSL certificate check, I can see a Dynatrace notification about DDU consumption. When I looked at  the DDU page, I could not find the SSL cert check consuming any DDU's. I was wondering if this was a fluke or if DDU's are actually being consumes and how I could see the consumption rates.

**Comment by ZTRossouw** [comment]
Custom metrics typically consume DDUs. However custom metrics from OneAgent-monitored hosts are first deducted from your quota of included metrics per host unit, so they don't necessarily deduct DDUs from your quota. The same is true for custom log metrics.

**Comment by juliusloman** [comment]
It does not consume any DDUs as it does not send any metrics. The extension only creates metadata and sends events info Dynatrace. It has a metric specified (number of certificates count), but there are no data sent (yet) for this metrics. It's only specified because the plugin needs at least one metric specified. If no measurements are sent for the metrics, it won't consume DDUs.
